name: tipitakaabidan
description: Tipitaka Pali-Myanmar Dictionary

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_widget_from_html_core: ^0.8.4
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.0+2
  path_provider: ^2.0.8
  path: ^1.8.0
  sharedpreference: ^0.0.1
  toggle_switch: ^1.3.0
  flutter_slidable: ^1.2.0
  # # pdf_render: ^1.0.23
  # native_pdf_renderer: ^4.0.1
  asset_pdf_viewer:
    # path: packages/asset_pdf_viewer_mobile
    path: packages/asset_pdf_viewer_desktop
  community_material_icon: ^5.9.55
  vs_scrollbar: ^0.2.1
  substring_highlight: ^1.0.33
  draggable_scrollbar: ^0.1.0
  equatable: ^2.0.3
  custom_pop_up_menu: ^1.2.3+1
  app_popup_menu: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: ^2.0.2

flutter_icons:
  # android: true
  # ios: true
  # remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#2b4e2c"
  image: "assets/icon/icon_circle.png"

flutter:
  uses-material-design: true

  assets:
    - assets/database/tipitaka_abidan.db
    - assets/books/covers/
    - assets/books/pdfs/
    - assets/info.html
